### ISSUE TITLE
parser 功能目前有哪些情况不支持的或待处理的吗？

### ISSUE THREAD

**Issue by wll8** [MrXujiang/xijs#1]
- 文档上说支持 函数、正则，那对于其他类型呢？例如 Date 啥啥的。
- 另外，如果类似 __xfunc__ 的前缀已被要序列号的数据使用了呢？但由于数据的不可知性，是无法知道哪个前缀会被占用的。
- 继上面问题之后：如果要实现 `获取代码中的片段` 功能是否可靠？

``` js
const obj = {
  a: 1,
  b() {
    // 这是一些注释
    console.log(123)
  },
}

// 如果获取 obj 的原始代码?
const code = getCode(obj)
// 输出以下字符串
```
code ===
``` txt
 {
  a: 1,
  b() {
    // 这是一些注释
    console.log(123)
  },
}
```

**Comment by MrXujiang** [comment]
> * 文档上说支持 函数、正则，那对于其他类型呢？例如 Date 啥啥的。
> * 另外，如果类似 **xfunc** 的前缀已被要序列号的数据使用了呢？但由于数据的不可知性，是无法知道哪个前缀会被占用的。
> * 继上面问题之后：如果要实现 `获取代码中的片段` 功能是否可靠？
> 
> ```js
> const obj = {
>   a: 1,
>   b() {
>     // 这是一些注释
>     console.log(123)
>   },
> }
> 
> // 如果获取 obj 的原始代码?
> const code = getCode(obj)
> // 输出以下字符串
> ```
> 
> code ===
> 
> ```
>  {
>   a: 1,
>   b() {
>     // 这是一些注释
>     console.log(123)
>   },
> }
> ```

目前前缀通过__xfunc__, __xreg__来隔离, 后期考虑用更优雅的方式优化,
问题二, 目前基于parse可以实现getCode(obj)的方式, 如果有更好的建议, 随时提pr和issue反馈,持续迭代~
